### ISSUE TITLE
Which version of Apollo of this patched one?

### ISSUE THREAD

**Issue by yellinshadows** [guardstrikelab/carla_apollo_bridge#105] opened 2023-05-30 02:46 UTC
Hi,

Is this following patched apollo version 7?

```
# Using SSH
git clone --branch guardstrike/apollo_carla_bridge git@github.com:guardstrikelab/apollo.git

#Using HTTPS
git clone --branch guardstrike/apollo_carla_bridge https://github.com/guardstrikelab/apollo.git
```

Thanks!

**Comment by meua** [comment] 2023-05-30 11:50
> Hi,
> 
> Is this following patched apollo version 7?
> 
> ```
> # Using SSH
> git clone --branch guardstrike/apollo_carla_bridge git@github.com:guardstrikelab/apollo.git
> 
> #Using HTTPS
> git clone --branch guardstrike/apollo_carla_bridge https://github.com/guardstrikelab/apollo.git
> ```
> 
> Thanks!

Here are two ways to pull the code through ssh or https, the effect is the same.

**Comment by WilliaJing** [comment] 2023-05-31 03:17
> 

@yellinshadows We made modifications to a version between 7.0 and 8.0，and we are planning to upgrade to 8.0.

**Comment by datvuthanh** [comment] 2023-05-31 09:58
@WilliaJing Could you guide me how to reproduce the original apollo repo to integrate with carla 0.9.14?

**Comment by WilliaJing** [comment] 2023-05-31 10:53
@datvuthanh you can try directly pulling the latest official code from Apollo
and not 
git clone --branch guardstrike/apollo_carla_bridge git@github.com:guardstrikelab/apollo.git

**Comment by datvuthanh** [comment] 2023-06-01 06:36
Hi @WilliaJing , thank you for your help. Do you use LGSVL Simulator? I want to build Full Self Driving Car System on Carla but concerning about carla support.

**Comment by WilliaJing** [comment] 2023-06-02 01:58
I haven't used LGSVL Simulator,it has stoped update,so I am trying to use carla.

**Comment by WilliaJing** [comment] 2023-06-15 03:25
It looks like this issue hasn’t been active in longer than a few weeks. In the absence of more information, we will close it, If you find that this is still a problem, please feel free to reopen it.

**Closed** 2023-06-16 12:06 UTC
