### ISSUE TITLE
车辆在apollo内反复闪动，在carla内不动

### ISSUE THREAD

**Issue by zhangs666** [guardstrikelab/carla_apollo_bridge#101] opened 2023-05-23 08:17 UTC
视频如下：

https://github.com/guardstrikelab/carla_apollo_bridge/assets/87601573/ec05af14-e9e3-4ad0-92bd-51d0309741f5

**Comment by PhilWallace** [comment] 2023-05-23 16:44
I met the exact same problem. Hope it will be fixed soon.

**Comment by WilliaJing** [comment] 2023-05-25 02:38
Hi,Only when you only turn on Sim Control, it is related to Apollo, which has nothing to do with Bridge.
You can close the Bridge container and only run the Apollo container to see.

**Comment by zhangs666** [comment] 2023-05-25 06:24
关掉了sim control之后车确实不会闪动，但是车不会动。以下是carla_spawn_objects.py的输出：
![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/87601573/22294174-f09a-482a-9e39-52549c42e39f)

**Comment by WilliaJing** [comment] 2023-05-25 08:44
> 关掉了sim control之后车确实不会闪动，但是车不会动。以下是carla_spawn_objects.py的输出： ![image](https://user-images.githubusercontent.com/87601573/240820799-22294174-f09a-482a-9e39-52549c42e39f.png)

This error is related to the conversion of carla radar messages.，we have fixed it in #85, Please wait for the code to be merged,
now you can ignore this error.
you can restart by following the steps,and you can observe if there are any other error messages?

**Comment by zhangs666** [comment] 2023-05-25 08:57
车辆不会移动。每当我点击一次“SETUP”，就会弹出一条之前的报错：

E0525 08:53:16.762575  6876 channel_manager.cc:326] [spawn_objects] newly added writer(belongs to node[conti_radar_front])'s message type[apollo.drivers.ContiRadar] does not match the exsited writer(belongs to node[cyber_bridge_node])'s message type[apollo.drivers.PointCloud].

但是车辆是一直没有移动的

![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/87601573/b11d97aa-e5f8-4830-a775-6c20e375a265)
![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/87601573/41ddfac4-2ada-4018-b8cb-0f3f25ca3153)
![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/87601573/a69f76dd-f04a-4cd4-9d31-8225f9642070)

**Comment by zhangs666** [comment] 2023-05-25 08:59
车辆不会移动。每当我点击一次“SETUP”，就会弹出一条之前的报错：

E0525 08:53:16.762575 6876 channel_manager.cc:326] [spawn_objects] newly added writer(belongs to node[conti_radar_front])'s message type[apollo.drivers.ContiRadar] does not match the exsited writer(belongs to node[cyber_bridge_node])'s message type[apollo.drivers.PointCloud].

但是车辆是一直没有移动的

![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/87601573/64517cd1-f7cf-41a2-bc25-45eda7eb4db0)

![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/87601573/bed7ffce-0be1-49df-9694-caf2edb24fd1)

![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/87601573/1c394cbc-6393-429e-8c41-9128afca088f)

**Comment by zhangs666** [comment] 2023-05-25 09:37
finish change to MKZ example and restart , the vehicle still can not move.

![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/87601573/65b79755-38a1-4e01-85b3-ec08241a96c8)

![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/87601573/d201c43c-0b40-4a39-8650-7012d3b76cbe)

**Comment by zhangs666** [comment] 2023-05-25 09:56
i found that everytime when i click "setup",the bridge.py says:
![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/87601573/262ae64c-d998-4d08-80a4-dfb84ddd31c8)
and the carla_spawn_objects.py says:
![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/87601573/ff406f9c-335b-44a6-b23a-a64ec50c4d27)

**Comment by PhilWallace** [comment] 2023-05-26 14:47
> 

I tried today and met the same problem... So sad. I might go to read the source code and try to find out why.

**Comment by zhangs666** [comment] 2023-05-28 12:08
> > 
> 
> I tried today and met the same problem... So sad. I might go to read the source code and try to find out why.

hello,do you find out why?

**Comment by PhilWallace** [comment] 2023-05-29 13:42
> > > 
> > 
> > 
> > I tried today and met the same problem... So sad. I might go to read the source code and try to find out why.
> 
> hello,do you find out why?

我之前的docker环境有一些问题（必须以sudo运行）。现在我重新调整了docker权限，跑通了，车可以动了，但是仍然有这个error信息。这个error讲的是电云和Radar信息不匹配，我猜测可能与其他页面提到的点云转了90度的bug有关。不过目前至少并不影响routing -> planning -> control这个数据流。希望官方尽早修吧。

你也可以看看你的docker是不是有问题，确保在host terminal下可以不用sudo直接运行。

**Comment by meua** [comment] 2023-05-30 02:08
> > > > 
> > > 
> > > 
> > > I tried today and met the same problem... So sad. I might go to read the source code and try to find out why.
> > 
> > 
> > hello,do you find out why?
> 
> 我之前的docker环境有一些问题（必须以sudo运行）。现在我重新调整了docker权限，跑通了，车可以动了，但是仍然有这个error信息。这个error讲的是点云和Radar信息不匹配，我猜测可能与其他页面提到的点云转了90度的bug有关。不过目前至少并不影响routing -> planning -> control这个数据流。希望官方尽早修吧。
> 
> 你也可以看看你的docker是不是有问题，确保在host terminal下可以不用sudo直接运行。

Please pay attention to this pr https://github.com/guardstrikelab/carla_apollo_bridge/pull/100, the problem is being fixed.

**Comment by PhilWallace** [comment] 2023-05-30 13:14
> finish change to MKZ example and restart , the vehicle still can not move.
> 
> ![image](https://user-images.githubusercontent.com/87601573/240870478-65b79755-38a1-4e01-85b3-ec08241a96c8.png)
> 
> ![image](https://user-images.githubusercontent.com/87601573/240870611-d201c43c-0b40-4a39-8650-7012d3b76cbe.png)

你可以试着在modules中手动启动prediction模块，再等几秒看看Module Delay中是否有数据。我今天又遇到车不动的问题，靠这个方法解决了。

**Comment by zhangs666** [comment] 2023-05-30 13:19
大概明后天会依此尝试这些方法，最近太忙了。非常感谢你！

**Comment by zhangs666** [comment] 2023-05-30 14:00
我调整了我的docker权限，但是我发现我的predition模块无法打开，当我打开prediction之后一段时间，它会自己关闭

**Comment by zhangs666** [comment] 2023-05-31 07:14
我发现我的planning,control没有module delay.我觉得怀疑可能是planning/control编译问题？或者是设备问题

**Comment by zhangs666** [comment] 2023-05-31 07:57
![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/87601573/e072937a-8a96-46d7-8593-e9a9baa853d8)

**Comment by zhangs666** [comment] 2023-05-31 07:58
![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/87601573/871990aa-b4b4-4588-a71d-7efdeddc4858)

**Comment by WilliaJing** [comment] 2023-05-31 08:02
You can try to close these three containers and execute them again by readme.txt.

**Comment by WilliaJing** [comment] 2023-05-31 08:10
I was wrong ,it's readme.md.

**Comment by zhangs666** [comment] 2023-05-31 08:18
my command  order is :

1. the carlasim/carla:0.9.14 container will auto-start when the computer is turned-on.so i do not have to run it by myself.

3. then i run apollo :

cd apollo
bash docker/scripts/dev_start.sh
bash docker/scripts/dev_into.sh
./scripts/bootstrap.sh

3.then the bridge:

cd carla_apollo_bridge/docker
./run_docker.sh

docker exec -ti carla_cyber_0.9.14 bash
./apollo.sh build_cyber opt (i have to do this everytime. if not , the bridge.py can not run normaly )
cd /apollo/cyber/carla_bridge
python carla_cyber_bridge/bridge.py

then open another terminal:

docker exec -ti carla_cyber_0.9.14 bash
cd /apollo/cyber/carla_bridge
python carla_spawn_objects/carla_spawn_objects.py


all the commands are above.

**Comment by WilliaJing** [comment] 2023-05-31 08:20
![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/50048416/48c7c60e-4f34-437c-ae77-5ac138ca1b0f)

**Comment by zhangs666** [comment] 2023-05-31 08:23
i have run this before. do i need to run this command everytime when i start co-simulation?

**Comment by WilliaJing** [comment] 2023-05-31 08:25
Under normal circumstances, there is no need to restart the Apollo container, 
but you are currently not working properly，so you can run again.

**Comment by zhangs666** [comment] 2023-05-31 08:33
when i run ./apollo.sh build_gpu in apollo container, i must add sudo. is that normal?

**Comment by PhilWallace** [comment] 2023-05-31 08:41
Here's what my modules like when the car could finally move:

![image](https://github.com/guardstrikelab/carla_apollo_bridge/assets/37956889/362f0920-6a9b-4600-b143-4ef8ee690c7d)

I had the same problem as yours. What I did is as follow:

1. select "Mkz Example" in --vehicle-- Before running the python scripts in bridge docker.
2. Click "Setup" in Quick Start.
3. I disabled the "Recorder" module in Modules, because it will consume too much space ("I'm not sure whether this step is related to this problem").
4. The "Prediction" module will fail to start, and I manually started this module in Module Controller.
5. I waited for a few seconds, and then there are data shown in Module Delay:

![Screenshot from 2023-06-01 01-30-42](https://github.com/guardstrikelab/carla_apollo_bridge/assets/37956889/c19064e5-8210-4fa8-ae09-9a3b9f03bc6e)

These steps works for me also after I reboot my system and dockers. This seems to be some problem in the Apollo docker itself. Hope there will be a more robust version soon.

**Comment by PhilWallace** [comment] 2023-05-31 08:45
> when i run ./apollo.sh build_gpu in apollo container, i must add sudo. is that normal?

For me, sudo is not needed in the docker. Maybe you can try to update or reinstall docker. Or use "sudo chown -R 1000:1000 /apollo" to set the execution privilege (not sure whether this will work).

**Comment by zhangs666** [comment] 2023-05-31 08:49
i will rebuild everything from the start.My environment is in a mess.come back later.

**Comment by meua** [comment] 2023-05-31 11:02
> when i run ./apollo.sh build_gpu in apollo container, i must add sudo. is that normal?
If your docker commands require sudo to run, you can avoid it by doing:
```bash
sudo usermod -aG docker $USER
sudo chmod 666 /var/run/docker.sock
systemctl restart docker
```

**Comment by zhangs666** [comment] 2023-06-10 02:13
问题最终解决了。环境没有任何问题，就是单纯的配置不行。后来我是使用rtx 3090很轻松就跑起来了。麻烦各位了，非常感谢

**Closed** 2023-06-10 02:13 UTC

**Comment by caixxuan** [comment] 2023-08-20 09:49
> > > > 
> > > 
> > > 
> > > I tried today and met the same problem... So sad. I might go to read the source code and try to find out why.
> > 
> > 
> > hello,do you find out why?
> 
> 我之前的docker环境有一些问题（必须以sudo运行）。现在我重新调整了docker权限，跑通了，车可以动了，但是仍然有这个error信息。这个error讲的是点云和Radar信息不匹配，我猜测可能与其他页面提到的点云转了90度的bug有关。不过目前至少并不影响routing -> planning -> control这个数据流。希望官方尽早修吧。
> 
> 你也可以看看你的docker是不是有问题，确保在host terminal下可以不用sudo直接运行。

>请问如何设置docker权限

**Comment by caixxuan** [comment] 2023-08-20 11:26
> 我调整了我的docker权限，但是我发现我的predition模块无法打开，当我打开prediction之后一段时间，它会自己关闭

我也无法打开，请问如何解决

**Comment by meua** [comment] 2023-08-22 00:47
> > 我调整了我的docker权限，但是我发现我的predition模块无法打开，当我打开prediction之后一段时间，它会自己关闭
> 
> 我也无法打开，请问如何解决

Please describe more details to reproduce your problem.

**Comment by caixxuan** [comment] 2023-08-22 02:40
> > > 我调整了我的docker权限，但是我发现我的predition模块无法打开，当我打开prediction之后一段时间，它会自己关闭
> > 
> > 
> > 我也无法打开，请问如何解决
> 
> Please describe more details to reproduce your problem.

the same as the question described before, the bridge is connected but the car cannot move at all, and the prediction cannot open, i have tried the method before, but it cannot work
