### ISSUE TITLE
No module named carla

### ISSUE THREAD

**Issue by charles-lei** [guardstrikelab/carla_apollo_bridge#41] opened 2023-01-12 10:01 UTC
### Discussed in https://github.com/orgs/guardstrikelab/discussions/40

<div type='discussions-op-text'>

<sup>Originally posted by **Saddy21** January 12, 2023</sup>
I am getting this error "**No module named carla**" when running:-
**_cd /apollo/cyber/carla_bridge
python carla_cyber_bridge/bridge.py_**
![Screenshot from 2023-01-12 14-59-27](https://user-images.githubusercontent.com/98169680/212030314-9b3a2d80-f39a-4f4d-9c4e-a69801d58847.png)

I checked the ip address of carla docker version it is using : **IPAddress: 172.18.0.2**.
![Screenshot from 2023-01-12 14-59-03](https://user-images.githubusercontent.com/98169680/212030441-d8fb5cd3-ff50-44f3-980a-6093413cfa6e.png)

While in the apollo cyber/setup.bash is using                     :**CYBER_IP=172.17.0.1**
![Screenshot from 2023-01-12 14-54-20](https://user-images.githubusercontent.com/98169680/212030493-156ce518-8a01-4369-a0f0-fca40e4b9db3.png)

Is it because of this this error or something else needs to be changed.I have followed all the steps in the documentation [.](https://github.com/guardstrikelab/carla_apollo_bridge)
Please help.

@guardstrikeo 
</div>

**Comment by yuting-fu** [comment] 2023-01-19 16:03
Hi, I had the same error. In my case, it was because I didn't have any of the compiled carla .whl and .egg files. I got a  lot of deleted files if I do git status. The[ files in this directory](https://github.com/guardstrikelab/carla_apollo_bridge/tree/master/src/carla_python/carla/dist) are too big to download for me, even with git-lfs. In the end I copied the missing files from a carla 0.9.13 docker container to this repo. Then everything works.

**Comment by noorzzz** [comment] 2023-01-23 21:18
Hi,
I notice that the intended [.egg file](https://github.com/guardstrikelab/carla_apollo_bridge/blob/master/src/carla_python/carla/dist/carla-0.9.13-py2.7-linux-x86_64.egg) is not downloaded properly using the command mentioned at the README.md. I did manage to make the bridge working by simply downloading the .egg file from the official Carla distribution. It seems to me that you can also try installing `git-lfs`, but I haven't checked that yet.

Hope this helps

**Comment by yuting-fu** [comment] 2023-01-24 08:14
Same here. Even if git-lfs is installed, I cannot pull the files because it's above the git-lfs file size limit. I copied all the .egg and .whl from the CARLA docker container to the intended path.

**Comment by Yandong-Luo** [comment] 2023-01-25 06:24
I also have the same question

**Comment by charles-lei** [comment] 2023-01-28 14:18
Hi guys, git lfs files cannot be downloaded properly cause github lfs free bandwidth limitation, you can copy those files from Carla's PythonAPI. This issue will be fixed by #47

**Comment by Yandong-Luo** [comment] 2023-01-30 00:38
> 

I have check the path in docker. The .egg file indeed exists in the correct path as shown as follow. But I still could not import carla. The issue is the same.

`root@36ab8b1149fe:/apollo/cyber/carla_bridge/carla_python/carla/dist# ls
carla-0.9.13-cp27-cp27mu-manylinux_2_27_x86_64.whl
carla-0.9.13-cp37-cp37m-manylinux_2_27_x86_64.whl
carla-0.9.13-py2.7-linux-x86_64.egg
carla-0.9.13-py3.6-linux-x86_64.egg
carla-0.9.13-py3.7-linux-x86_64.egg
carla-0.9.13-py3.9-linux-x86_64.egg`

**Comment by guardstrikeo** [comment] 2023-02-10 13:31
fixed by #50

**Closed by guardstrikeo** 2023-02-10 13:31 UTC
Labels: bug
